services:
  postgres-db:
    image: postgres:17-alpine
    container_name: cc_db
    environment:
      POSTGRES_DB: ccdb
      POSTGRES_USER: ccuser
      POSTGRES_PASSWORD: ccpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cc-net

  spring-app-dev:
    image: docker.io/library/maven:4.0.0-rc-5-eclipse-temurin-25-alpine
    container_name: cc_dev
    volumes:
      - .:/app
      - maven_cache:/root/.m2
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/ccdb
      - SPRING_DATASOURCE_USERNAME=ccuser
      - SPRING_DATASOURCE_PASSWORD=ccpass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - SPRING_MAIL_HOST=mailpit_container
      - SPRING_MAIL_PORT=1025
    command: >
      mvn -f /app/pom.xml 
      org.springframework.boot:spring-boot-maven-plugin:4.0.6:run 
      -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    depends_on:
      - postgres-db
    networks:
      - cc-net

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit_container
    ports:
      - "1025:1025" # SMTP server port
      - "8025:8025" # Web UI port
    networks:
      - cc-net

volumes:
  postgres_data:
  maven_cache:

networks:
  cc-net:
    driver: bridge
