CREATE TABLE users (
	uid UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	username VARCHAR(50) NOT NULL UNIQUE,
	email VARCHAR(100) NOT NULL UNIQUE,
	verified BOOLEAN NOT NULL DEFAULT FALSE,
	password VARCHAR(255) NOT NULL,
	calendar_notify BOOLEAN NOT NULL DEFAULT TRUE,
	invite_notify BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE groups (
	uid UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	name VARCHAR(100) NOT NULL
);

CREATE TABLE events (
	uid UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	name VARCHAR(150) NOT NULL,
	start_time TIMESTAMP NOT NULL,
	end_time TIMESTAMP NOT NULL,
	frequency VARCHAR(50),
	until TIMESTAMP
);

CREATE TABLE notify (
	uid UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	user_uid UUID REFERENCES users(uid) ON DELETE CASCADE,
	event_uid UUID REFERENCES events(uid) ON DELETE CASCADE,
	notify_email BOOLEAN NOT NULL DEFAULT TRUE,
	notify_inapp BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE notifications (
	uid UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	notify_user_uid UUID NOT NULL,
	notify_event_uid UUID NOT NULL,
	type VARCHAR(50) NOT NULL,
	status VARCHAR(50) NOT NULL,
	scheduled_for TIMESTAMP NOT NULL,
	retries INT NOT NULL DEFAULT 0,
	seen BOOLEAN NOT NULL DEFAULT FALSE,
	notify_uid UUID REFERENCES notify(uid) ON DELETE CASCADE
);

CREATE TABLE invites (
	uid UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	user_id UUID NOT NULL REFERENCES users(uid) ON DELETE CASCADE,
	group_id UUID NOT NULL REFERENCES groups(uid) ON DELETE CASCADE,
	status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE user_groups (
	uid UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	user_id UUID REFERENCES users(uid) ON DELETE CASCADE,
	group_id UUID REFERENCES groups(uid) ON DELETE CASCADE,
	role VARCHAR(50) NOT NULL DEFAULT 'MEMBER',
	notify BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE group_events (
	uid UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	group_id UUID REFERENCES groups(uid) ON DELETE CASCADE,
	event_id UUID REFERENCES events(uid) ON DELETE CASCADE
);
